"""Add bottle variants to the data model for bottles

Revision ID: 0800e47ed991
Revises: a667c7e6a14c
Create Date: 2025-12-03 03:01:34.944950+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0800e47ed991'
down_revision: Union[str, Sequence[str], None] = 'a667c7e6a14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_variant column with default value for existing rows
    op.add_column('bottles', sa.Column('is_variant', sa.Boolean(), nullable=True, server_default='false'))
    # Update existing rows to set is_variant = False (they're all base bottles)
    op.execute("UPDATE bottles SET is_variant = false WHERE is_variant IS NULL")
    # Now make the column NOT NULL
    op.alter_column('bottles', 'is_variant', nullable=False, server_default=None)
    op.add_column('bottles', sa.Column('parent_bottle_id', sa.Integer(), nullable=True))
    op.add_column('bottles', sa.Column('barrel_number', sa.String(length=100), nullable=True))
    op.add_column('bottles', sa.Column('warehouse', sa.String(length=50), nullable=True))
    op.add_column('bottles', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.add_column('bottles', sa.Column('vintage_year', sa.Integer(), nullable=True))
    op.add_column('bottles', sa.Column('proof_actual', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('bottles', sa.Column('age_statement_actual', sa.String(length=50), nullable=True))
    op.add_column('bottles', sa.Column('pick_information', sa.String(), nullable=True))
    op.add_column('bottles', sa.Column('tier_run', sa.String(length=50), nullable=True))
    op.add_column('bottles', sa.Column('bottle_date', sa.Date(), nullable=True))
    op.add_column('bottles', sa.Column('release_info', sa.String(), nullable=True))
    op.create_foreign_key(None, 'bottles', 'bottles', ['parent_bottle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bottles', type_='foreignkey')
    op.drop_column('bottles', 'release_info')
    op.drop_column('bottles', 'bottle_date')
    op.drop_column('bottles', 'tier_run')
    op.drop_column('bottles', 'pick_information')
    op.drop_column('bottles', 'age_statement_actual')
    op.drop_column('bottles', 'proof_actual')
    op.drop_column('bottles', 'vintage_year')
    op.drop_column('bottles', 'batch_number')
    op.drop_column('bottles', 'warehouse')
    op.drop_column('bottles', 'barrel_number')
    op.drop_column('bottles', 'parent_bottle_id')
    op.drop_column('bottles', 'is_variant')
    # ### end Alembic commands ###
